defaults:
    - _self_
    - model: custom

system:
    device: cpu

data:
    data_dir: /Users/akshay/nanogpt/src/data/datasets/shakespeare/
    batch_size: 4
    block_size: 32


algorithm:
    lr: 3e-4