defaults:
    - _self_
    - model: gpt2

settings:
    device: cuda

data:
    data_dir: /Users/akshay/nanogpt/src/data/datasets/shakespeare/
    block_size: 200
    batch_size: 32

algorithm:
    lr: 1.0
    warmup: 3000
    accum_iter: 10
    smoothing: 0.1
    epochs: 8