defaults:
    - _self_
    - model: gpt2

data:
    dataset_path: /Users/akshay/canvas/src/data/dataset/multi30k/
    vocab_path: /Users/akshay/canvas/src/data/dataset/vocab.pt
    max_padding: 72
    batch_size: 32

algorithm:
    lr: 1.0
    warmup: 3000
    accum_iter: 10
    smoothing: 0.1
    epochs: 8