defaults:
    - _self_
    - model: custom

system:
    device: cuda
    to_compile: True

data:
    data_dir: /scratch/ar8692/nanogpt/src/data/datasets/shakespeare
    batch_size: 32
    block_size: 1024


algorithm:
    lr: 3e-4